quotes = [
"Whatever you do, do it well. – Walt Disney",
"Be so good they can’t ignore you. – Steve Martin",
"There is no substitute for hard work. – Thomas Edison",
"All limitations are self-imposed. – Oliver Wendell Holmes",
"Strive for greatness. – Lebron James",
"May your choices reflect your hopes, not your fears. – Nelson Mandela",
"What we think, we become. – Buddha",
"Problems are not stop signs, they are guidelines. – Robert H. Schuller",
"Happiness depends upon ourselves. – Aristotle",
"Determine your priorities and focus on them. – Eileen McDargh",
"If you tell the truth you don’t have to remember anything. – Mark Twain",
"Simplicity is the ultimate sophistication. – Leonardo da Vinci",
"Never regret anything that made you smile. – Mark Twain",
"Imitation is suicide. – Ralph Waldo Emerson",
"Life is 10 percent what happens to you and 90 percent how you respond to it. – Lou Holtz",
"I will not let anyone walk through my mind with their dirty feet. – Mahatma Gandhi",
"Do what you can, with what you have, where you are. – Theodore Roosevelt",
"Be yourself; everyone else is already taken. – Oscar Wilde",
"In three words I can sum up everything I've learned about life. It goes on. – Robert Frost",
"Do not go where the path may lead; go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
"You must be the change you wish to see in the world. – Mahatma Gandhi",
"We don’t laugh because we’re happy – we’re happy because we laugh. – William James",
"The best way to cheer yourself is to try to cheer someone else up. – Mark Twain",
"The foolish man seeks happiness in the distance, the wise grows it under his feet. – James Oppenheim",
"What you do not want done to yourself, do not do to others. — Confucius",
"Happy people plan actions, they don’t plan results. — Dennis Waitley",
"Happiness is when what you think, what you say, and what you do are in harmony. — Mahatma Gandhi",
"There are more things to alarm us than to harm us, and we suffer more often in apprehension than reality.” — Seneca",
"I attribute my success to this: I never gave or took any excuse. – Florence Nightingale",
"The secret of success in life is for a man to be ready for his opportunity when it comes. – Benjamin Disraeli",
"Don't let what you cannot do interfere with what you can do. – John R. Wooden",
"To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
"Success is the sum of small efforts, repeated day-in, and day-out. – Robert Collier",
"No one can make you feel inferior without your consent. – Eleanor Roosevelt",
"What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
"Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein"
]
